# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: 'REUSE Compliance Check'
description: "Check your project's REUSE compliance for clear and simple licensing and copyright!"
author: 'Free Software Foundation Europe (FSFE)'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  summary:
    description: "Show your REUSE compliance report in the github step summary using markdown (`markdown`), a json codeblock (`json`) or not at all (`none`)"
    required: true
    default: 'markdown'

