# SPDX-FileCopyrightText: 2020 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Use local file to test against itself
  test-self:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE version
      uses: ./
      with:
        args: --version
    - name: REUSE lint
      uses: ./
      with:
        args: --include-submodules lint --json
    - name: REUSE SPDX SBOM
      uses: ./
      with:
        args: spdx

  # Use all major version of the action
  test-v1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
      with:
        args: lint
  test-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
      with:
        args: lint --json
  test-v3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v3
      with:
        args: lint --json
  test-v4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v4
      with:
        args: lint --json
  test-v5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
      with:
        args: lint --json
